---
- name: Install r1soft agent
  hosts: target
  become: yes
  become_method: sudo 
  tasks: 
# this line is for centos 7
    - block:
      - name: Create a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: latest
        notify: R1SOFT-INSTALLED_ON_CENTOS_7
    
    
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
  
  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_7
      systemd:
         name: sbm-agent
         state: restarted

# this line is for centos 6
    - block:
      - name: Create a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: latest
        notify: R1SOFT-INSTALLED_ON_CENTOS_6
      
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_6
      systemd:
         name: sbm-agent
         state: restarted
    

      # this line is for centos 8
    - block:
      - name: Create a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: latest
        notify: R1SOFT-INSTALLED_ON_CENTOS_8
      
    
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  
  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_8
      systemd:
         name: sbm-agent
         state: restarted

       # this line is for centos Fedora
    - block:
      - name: Create a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: latest
        notify: R1SOFT-INSTALLED_ON_FEDORA_28
      
    
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "28"
  
  handlers:
    - name: R1SOFT-INSTALLED_ON_FEDORA_28
      systemd:
         name: sbm-agent
         state: restarted