---
- name: Install r1soft agent
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
# this line is for centos 7
    
      - name: Created a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: state
        
    
    
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
        notify: R1SOFT-INSTALLED_ON_CENTOS_7

  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_7
      systemd:
         name: sbm-agent
         state: restarted

# this line is for centos 6
    
      - name: Created a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: present
       
      
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
        notify: R1SOFT-INSTALLED_ON_CENTOS_6

  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_6
      systemd:
         name: sbm-agent
         state: restarted