---
- name: Install r1soft agent
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
# this line is for centos 7
    - block:
      - name: Created a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: state
        notify: R1SOFT-INSTALLED_ON_CENTOS_7
    
    
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
  
  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_7
      systemd:
         name: sbm-agent
         state: restarted

# this line is for centos 6
    - block:
      - name: Created a Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo
    
      - name: Install r1soft agent
        package:
          name: serverbackup-enterprise-agent 
          state: present
        notify: R1SOFT-INSTALLED_ON_CENTOS_6
      
      - name: Get key
        shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

  handlers:
    - name: R1SOFT-INSTALLED_ON_CENTOS_6
      systemd:
         name: sbm-agent
         state: restarted